"""
Cost-aware optimizer: objective, inputs, and constraint logic
=============================================================

This module solves portfolio-rebalancing problems that trade off four forces:
1) expected return / signal reward,
2) portfolio risk,
3) linear trading costs from crossing the bid-ask spread,
4) nonlinear market-impact costs from trading too much size in illiquid names.

The optimizer works in WEIGHT space. That means all trade sizes are measured
as changes in portfolio weights, not raw shares.

----------------------------------------------------------------------
Core notation
----------------------------------------------------------------------

w = new portfolio weights to solve for
w_prev = previous portfolio weights before rebalancing
delta = w - w_prev = trade vector in weight space
alpha = expected-return signal for each stock
Sigma = covariance matrix of stock returns
lambda_risk = strength of the variance penalty
s_i = one-way linear trading-cost input for stock i

In this project, the preferred source is the stock-specific 'spread_oneway'
column passed in from the weekly transaction-cost file.

ADV_i = forecast average DAILY dollar volume for stock i
sigma_i = forecast DAILY return volatility for stock i
execution_days = number of trading days over which one rebalance is executed
AUM = assumed assets under management in dollars
eta_linear = multiplier on the linear spread-cost term
eta_impact = multiplier on the nonlinear impact-cost term
impact_kappa = scale parameter for impact coefficients
p = nonlinear impact exponent (default 1.5)
eps = smoothing constant used to make absolute-value penalties differentiable

----------------------------------------------------------------------
Economic objective
----------------------------------------------------------------------

The alpha-driven solver is economically trying to choose weights that maximize:

    alpha' w
    - lambda_risk * w' Sigma w
    - eta_linear * sum_i s_i * |delta_i|
    - eta_impact * sum_i c_i * |delta_i|^p

where:
    delta_i = w_i - w_prev_i
    c_i = stock-specific impact coefficient

In the actual code, the optimizer is written in smooth minimization form:

    J(w) = 0.5 * w' G w
           - alpha' w
           + eta_linear * sum_i s_i * sqrt(delta_i^2 + eps^2)
           + eta_impact * sum_i c_i * (delta_i^2 + eps^2)^(p/2)

with:
    G = 2 * lambda_risk * Sigma

Interpretation of each term:
- alpha' w:
  Rewards the optimizer for holding names with stronger signals.

- lambda_risk * w' Sigma w:
  Penalizes portfolios with high variance and with concentrations in names
  that co-move strongly.

- eta_linear * sum_i s_i * |delta_i|:
  Linear trading cost. This models crossing the spread. It grows in direct
  proportion to trade size.

- eta_impact * sum_i c_i * |delta_i|^p:
  Nonlinear market impact. This models the idea that trading more size becomes
  disproportionately expensive, especially in volatile and illiquid stocks.

----------------------------------------------------------------------
How spread_oneway is calculated upstream
----------------------------------------------------------------------

This file does NOT calculate the spread from raw bid/ask quotes.
It expects the caller to pass a one-way spread series through
'spreads_oneway'.

In this project, the raw daily one-way spread is constructed upstream as:

    spread_oneway_raw = 0.5 * (Ask - Bid) / ((Ask + Bid) / 2)

Explanation:
- (Ask - Bid) / midpoint gives the full quoted relative spread.
- Multiplying by 0.5 converts that full spread into a ONE-WAY execution cost.

Then the weekly transaction-cost pipeline smooths that daily series and
usually uses a lagged 20-day rolling median as the canonical weekly spread
input:

    spread_oneway_20d = lagged rolling median of spread_oneway_raw
                        over the past 20 trading days

The optimizer then receives this stock-specific 'spread_oneway' input and
uses it as s_i in the linear cost term.

So, in this file:
    s_i = spreads_oneway[i]

and the linear cost contribution for stock i is:
    eta_linear * s_i * |delta_i|

----------------------------------------------------------------------
How the nonlinear impact coefficient is calculated
----------------------------------------------------------------------

The nonlinear impact coefficient is built from the execution-window volume:

    execution_volume_i = execution_days * ADV_i
    c_i = impact_kappa * sigma_i * sqrt(AUM / execution_volume_i)

For the main weekly specification in this project, execution_days = 1.  The
portfolio is still re-decided only once per week; execution_days describes how
quickly the trade generated by that weekly decision is worked in the market.

Interpretation:
- sigma_i:
  More volatile stocks are more expensive to trade aggressively.
- ADV_i:
  Less liquid stocks are more expensive to trade aggressively.
- execution_days:
  A longer execution window makes more market volume available.  Under the
  maintained square-root implementation, impact falls with the square root of
  execution_days.  The main specification fixes this at one trading day.
- AUM:
  Larger funds create larger market footprint for the same weight change.
- impact_kappa:
  Global scaling knob for the whole impact model.

So the nonlinear impact penalty becomes more severe when:
- volatility is high,
- liquidity is low,
- AUM is large,
- trade size is large.

----------------------------------------------------------------------
Position ADV caps and trade ADV caps
----------------------------------------------------------------------

The optimizer enforces feasibility using ADV-based bounds in weight space.

1) Position ADV cap

This caps the MAXIMUM absolute position size based on liquidity:

    pos_cap_i = pos_adv_cap * ADV_i / AUM

Interpretation:
- If a stock trades 5 million dollars of ADV,
- and AUM is 100 million dollars,
- and pos_adv_cap = 0.20,

then:

    pos_cap_i = 0.20 * 5,000,000 / 100,000,000 = 0.01

So the optimizer will not allow that stock to exceed 1% portfolio weight.

This is a cap on TOTAL position size.

2) Trade ADV cap

This caps how much the portfolio can change in one rebalance:

    execution_volume_i = execution_days * ADV_i
    trade_cap_i = trade_adv_cap * execution_volume_i / AUM

Then the optimizer constrains:

    w_i >= w_prev_i - trade_cap_i
    w_i <= w_prev_i + trade_cap_i

Interpretation:
- even if the desired target weight is far away,
- the optimizer cannot jump there in one step if doing so would require too
  much trading relative to the stock's liquidity.

This is a cap on TRADE SIZE, not on the final position.  The position cap
continues to use one day of ADV as an inventory/liquidity measure; only the
trade cap and nonlinear impact term use the execution-window volume.

----------------------------------------------------------------------
Other constraints
----------------------------------------------------------------------

The solver also enforces:
- long_only:
  If True, weights cannot go below zero.
- dollar_neutral:
  If True, the sum of weights must equal 0 instead of 1.
- box_abs:
  Per-stock hard bound on absolute weight.
- gross_target:
  For long-short portfolios, weights can be rescaled to hit a target gross
  exposure and then projected back into the feasible set.

This rewritten version also supports partial fill for long-only sleeves:
- if the requested long-only target sum is infeasible under the ADV caps,
- the solver can stage into the position at the maximum feasible sum instead
  of crashing outright.

That behavior is used by the target-tracking TC strategies and can also be
used by the alpha-driven TC Markowitz strategies.

----------------------------------------------------------------------
Two solver types in this file
----------------------------------------------------------------------

1) solve_cost_aware_nonlinear_pg(...)

This is the ALPHA-DRIVEN solver. It chooses weights directly by balancing:
- alpha reward,
- covariance risk,
- linear spread cost,
- nonlinear impact cost.

Use this when the portfolio is being chosen endogenously from signal strength.

2) solve_rebalance_to_target_nonlinear_pg(...)

This is the TARGET-TRACKING solver. Instead of using a free alpha vector, it
builds a quadratic penalty around a fixed desired target portfolio:

    0.5 * target_penalty * || w - scaled_target ||^2

up to an additive constant that does not affect the optimizer.

In code, that is written as:

    G = target_penalty * I
    alpha_vec = target_penalty * scaled_target

This makes the optimizer ask:

    "What is the cheapest feasible way to move from w_prev toward w_target,
    given spread, impact, and ADV constraints?"

This is used for methods such as:
- equal-weight target tracking,
- value-weight target tracking.

----------------------------------------------------------------------
Numerical method
----------------------------------------------------------------------

The optimizer uses smooth constrained optimization on the same economic
objective described above.

The alpha-driven solver now uses projected L-BFGS with Armijo backtracking.
That means it:
1) starts from a feasible warm start near w_prev,
2) evaluates the smooth objective and gradient,
3) builds a low-memory inverse-Hessian approximation from recent iterates,
4) proposes a quasi-Newton step,
5) projects the candidate back onto the feasible set,
6) accepts or shrinks the step using Armijo backtracking,
7) falls back to a safeguarded projected-gradient method if needed.

The target-tracking solver keeps the simpler projected-gradient path, but now
uses a Barzilai-Borwein step-size guess and still keeps Armijo as a safeguard.

The smoothing term eps is used only to make the absolute-value penalties
differentiable and numerically stable.

Economically, the model is still the same linear spread cost plus nonlinear
impact cost. Only the numerical optimizer has changed.

----------------------------------------------------------------------
Ex-post realized cost breakdown
----------------------------------------------------------------------

The helper 'compute_trade_cost_breakdown(...)' computes realized costs after a
solution has been found.

It reports:
- linear_cost
- impact_cost
- total_cost

with:

    linear_cost = sum_i s_i * |delta_i|

and, when sigma and ADV are supplied,

    impact_cost = sum_i c_i * |delta_i|^p

This is useful for diagnostics because it separates:
- cost from crossing the spread,
- cost from market impact.

----------------------------------------------------------------------
Why the numerical method was upgraded
----------------------------------------------------------------------

The original implementation used smooth projected gradient descent with
Armijo backtracking for all transaction-cost problems. That method is robust,
but it can be slow when the risk term is strongly curved, because it only uses
first-order information and may need many small steps plus repeated
backtracking before making progress.

In this project, the covariance matrix supplied to the optimizer is repaired
upstream so that the quadratic risk block is treated as positive definite in
practice. Combined with:
- lambda_risk > 0,
- nonnegative spread inputs,
- nonnegative impact coefficients,
- impact exponent p >= 1,
- and convex box / sum / ADV-based constraints,

the smooth long-only transaction-cost problem is well behaved and is treated as
a strongly convex constrained optimization problem for numerical purposes.

That matters because a strongly convex objective has a unique optimum and much
more reliable local curvature. In that setting, a quasi-Newton method can use
curvature information to reach the same solution much faster than plain
projected gradient descent.

For that reason, the alpha-driven solver now uses projected L-BFGS.

Projected L-BFGS:
- keeps the SAME economic objective,
- keeps the SAME feasibility projection,
- keeps the SAME transaction-cost model,
- but replaces the raw gradient direction with a low-memory quasi-Newton
  direction that approximates second-order curvature.

This is a numerical acceleration, not an economic model change.

----------------------------------------------------------------------
Why projected L-BFGS was chosen
----------------------------------------------------------------------

Projected L-BFGS was chosen because it improves speed while preserving the
underlying optimization problem.

Relative to plain projected gradient descent, it:
- usually requires far fewer iterations,
- handles ill-conditioning better,
- makes better use of curvature from the covariance term,
- and works especially well when the solution is warm-started from w_prev.

The method is "projected" because the raw quasi-Newton candidate is still
mapped back into the feasible region after each trial step, so the final
iterate always respects the same box, sum, and ADV-based trading constraints.

Armijo backtracking is still kept as a safeguard. Its role is not to define the
main search direction, but to ensure that each accepted projected step produces
sufficient decrease in the smooth objective.

----------------------------------------------------------------------
Why the target-tracking solver was treated differently
----------------------------------------------------------------------

The target-tracking solver is numerically easier than the alpha-driven solver.

That is because its quadratic block is:

    G = target_penalty * I

instead of the full covariance-scaled matrix. Since that quadratic block is
already well conditioned relative to the Markowitz case, the simpler projected
gradient framework remains adequate there.

However, its step initialization was improved using a Barzilai-Borwein step
guess. This gives the projected-gradient solver a better local scaling without
changing the objective or constraints. Armijo backtracking is still kept as the
acceptance safeguard.

So:
- alpha-driven solver -> projected L-BFGS
- target-tracking solver -> projected gradient with BB step guess + Armijo

This keeps the implementation simple where possible and more powerful only
where needed.

----------------------------------------------------------------------
Why the preconditioning does not change the economics
----------------------------------------------------------------------

A diagonal curvature scaling is used internally as the initial inverse-Hessian
scale for the quasi-Newton method.

This does NOT replace Sigma.
This does NOT shrink or re-estimate the covariance matrix.
This does NOT change the optimization objective.

It only changes how the solver measures step lengths across coordinates.

In other words:
- changing regularization would change the problem,
- changing the preconditioner changes only the numerical path used to solve
  the same problem.

This was chosen specifically to improve conditioning without materially
changing the portfolio that solves the original economic objective.

----------------------------------------------------------------------
Fallback behavior
----------------------------------------------------------------------

The original safeguarded projected-gradient method is still retained as a
fallback.

If the quasi-Newton update becomes numerically unreliable, if curvature pairs
are not usable, or if a stable descent step cannot be accepted, the solver can
fall back to the more conservative projected-gradient path.

This keeps the implementation robust while allowing the faster quasi-Newton
method to handle the common well-conditioned cases.

----------------------------------------------------------------------
Economic interpretation after the upgrade
----------------------------------------------------------------------

The upgrade does NOT change the economics of the model.

The optimizer is still solving the same trade-off between:
- signal reward,
- variance control,
- spread crossing cost,
- nonlinear market impact,
- and explicit liquidity-based feasibility constraints.

So the economic interpretation remains:

    maximize signal net of risk net of realistic trading frictions

The only change is that the solver now reaches that solution more efficiently.

----------------------------------------------------------------------
Practical summary
----------------------------------------------------------------------

This optimizer is designed to prevent the portfolio from over-trading.

It will trade less aggressively when a stock has:
- a wide spread,
- low ADV,
- high volatility,
- large required trade size.

It will allow larger trades when:
- the signal is strong,
- the stock is liquid,
- volatility is lower,
- the resulting portfolio is still feasible under the ADV-based caps.

So the model is not simply "maximize alpha."

It is:

    maximize signal net of risk net of realistic trading frictions.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence, Tuple, Union
import warnings

import numpy as np
import pandas as pd


@dataclass
class CostAwareParams:
    """Configuration for nonlinear cost-aware portfolio optimization."""

    lambda_risk: float = 10.0
    eta_tc: float = 1.0
    eta_linear: Optional[float] = None
    eta_impact: float = 1.0
    impact_kappa: float = 1.0
    impact_exponent: float = 1.5
    impact_smooth_eps: float = 1e-5
    spread_bps_default: float = 10.0
    dollar_neutral: bool = False
    long_only: bool = True
    gross_target: float = 1.0
    pos_adv_cap: float = 0.05
    trade_adv_cap: float = 0.20
    # Number of trading days used to execute each scheduled rebalance.
    # Main project convention: weekly decisions, one-trading-day execution.
    execution_days: float = 1.0
    box_abs: float = 0.10
    target_penalty: float = 100.0
    max_iters: int = 2000
    step: float = 0.1
    tol: float = 1e-6
    max_backtracks: int = 12
    allow_partial_long_only: bool = True

    # Resolve the effective linear-cost multiplier while preserving the eta_tc alias.
    def resolved_eta_linear(self) -> float:
        if self.eta_linear is not None:
            return float(self.eta_linear)
        return float(self.eta_tc)

    # Validate and return the explicit execution horizon in trading days.
    def resolved_execution_days(self) -> float:
        days = float(self.execution_days)
        if (not np.isfinite(days)) or days <= 0.0:
            raise ValueError("execution_days must be a finite positive number of trading days.")
        return days


@dataclass
class TradeCostBreakdown:
    """Container for ex-post realized trade-cost components."""

    linear_cost: float
    impact_cost: float
    total_cost: float


# Canonicalize Series asset identifiers to the package-wide string convention.
def _canonical_series(x: pd.Series, *, name: str) -> pd.Series:
    out = pd.Series(x).copy()
    out.index = pd.Index(out.index).astype(str)
    if out.index.has_duplicates:
        dup = out.index[out.index.duplicated(keep=False)].unique().tolist()[:5]
        raise ValueError(f"{name} contains duplicate asset identifiers after string canonicalization: {dup}")
    return out


# Coerce a pandas object or array-like input into a dense float vector aligned to idx.
def _coerce_vector(
    x: Optional[Union[pd.Series, Sequence[float], np.ndarray]],
    idx: pd.Index,
    *,
    fill_value: float = 0.0,
) -> np.ndarray:
    if x is None:
        return np.full(len(idx), float(fill_value), dtype=float)
    if isinstance(x, pd.Series):
        use = _canonical_series(x, name="input series")
        return pd.to_numeric(use.reindex(idx), errors="coerce").fillna(fill_value).to_numpy(dtype=float)
    arr = np.asarray(x, dtype=float)
    if arr.ndim != 1 or arr.shape[0] != len(idx):
        raise ValueError(f"Expected a length-{len(idx)} vector; got shape {arr.shape}")
    arr = arr.copy()
    arr[~np.isfinite(arr)] = float(fill_value)
    return arr


# Resolve one-way linear trading costs in fraction-of-notional units.
def _resolve_spreads_fraction(
    idx: pd.Index,
    *,
    spreads_oneway: Optional[Union[pd.Series, Sequence[float], np.ndarray]] = None,
    spreads_bps: Optional[Union[pd.Series, Sequence[float], np.ndarray]] = None,
    default_bps: float = 10.0,
) -> np.ndarray:
    if spreads_oneway is not None:
        s = _coerce_vector(spreads_oneway, idx, fill_value=np.nan)
        if not np.isfinite(s).all():
            raise RuntimeError("Cost-aware optimizer received missing or non-finite spreads_oneway inputs.")
        if (s < 0).any():
            raise RuntimeError("Cost-aware optimizer received negative spreads_oneway inputs.")
        return s.astype(float, copy=False)
    if spreads_bps is not None:
        s_bps = _coerce_vector(spreads_bps, idx, fill_value=np.nan)
        if not np.isfinite(s_bps).all():
            raise RuntimeError("Cost-aware optimizer received missing or non-finite spreads_bps inputs.")
        if (s_bps < 0).any():
            raise RuntimeError("Cost-aware optimizer received negative spreads_bps inputs.")
        return s_bps.astype(float, copy=False) * 1e-4
    if default_bps is None:
        raise RuntimeError("Cost-aware optimizer requires explicit spread inputs; no default spread was provided.")
    return np.full(len(idx), float(default_bps) * 1e-4, dtype=float)


# Resolve the volatility vector used in the nonlinear impact term.
def _resolve_sigma_vector(
    idx: pd.Index,
    sigma: Optional[Union[pd.Series, Sequence[float], np.ndarray]],
    *,
    fill_value: float = 0.0,
) -> np.ndarray:
    return np.clip(np.abs(_coerce_vector(sigma, idx, fill_value=fill_value)), 0.0, None)


# Resolve and validate ADV inputs used for position, trade, and impact scaling.
def _resolve_adv_vector(
    idx: pd.Index,
    adv: Union[pd.Series, Sequence[float], np.ndarray],
    *,
    floor: float = 1.0,
) -> np.ndarray:
    out = _coerce_vector(adv, idx, fill_value=np.nan)
    if not np.isfinite(out).all():
        raise RuntimeError("Cost-aware optimizer received missing or non-finite ADV inputs.")
    if (out <= 0).any():
        raise RuntimeError("Cost-aware optimizer received non-positive ADV inputs.")
    return np.clip(out.astype(float, copy=False), floor, None)


# Return the default requested target sum implied by the configuration.
def _requested_target_sum(params: CostAwareParams) -> float:
    return 0.0 if params.dollar_neutral else 1.0


# Build the effective lower and upper weight bounds plus feasible sum statistics.
def _compute_bounds_stats(
    *,
    n: int,
    w_prev: np.ndarray,
    adv_vec: np.ndarray,
    aum: float,
    params: CostAwareParams,
) -> Tuple[np.ndarray, np.ndarray, float, float, float]:
    requested_target_sum = _requested_target_sum(params)

    if params.long_only:
        base_low = np.zeros(n, dtype=float)
        base_high = np.full(n, float(params.box_abs), dtype=float)
    else:
        base_low = -np.full(n, float(params.box_abs), dtype=float)
        base_high = np.full(n, float(params.box_abs), dtype=float)

    pos_cap = np.full(n, np.inf, dtype=float)
    if np.isfinite(params.pos_adv_cap) and params.pos_adv_cap > 0:
        pos_cap = float(params.pos_adv_cap) * (adv_vec / max(float(aum), 1.0))
        base_high = np.minimum(base_high, pos_cap)
        if not params.long_only:
            base_low = np.maximum(base_low, -pos_cap)

    # The position cap above is deliberately expressed in DAILY ADV units.
    # The trade cap instead uses the volume available during the execution
    # window.  With execution_days=1 this is exactly the previous behavior.
    execution_days = params.resolved_execution_days()
    execution_volume = adv_vec * execution_days
    trade_cap = np.full(n, np.inf, dtype=float)
    if np.isfinite(params.trade_adv_cap) and params.trade_adv_cap > 0:
        trade_cap = float(params.trade_adv_cap) * (execution_volume / max(float(aum), 1.0))

    low_trade = w_prev - trade_cap
    high_trade = w_prev + trade_cap

    low = np.maximum(base_low, low_trade)
    high = np.minimum(base_high, high_trade)

    # Grandfather legacy positions that currently violate static caps.
    # These positions should be allowed to drift back within the one-period
    # trade cap rather than becoming immediately infeasible.
    eps = 1e-12
    over_high = w_prev > (base_high + eps)
    if np.any(over_high):
        high[over_high] = np.maximum(high[over_high], np.minimum(w_prev[over_high], high_trade[over_high]))
        low[over_high] = np.minimum(low[over_high], high[over_high])

    if not params.long_only:
        under_low = w_prev < (base_low - eps)
        if np.any(under_low):
            low[under_low] = np.minimum(low[under_low], np.maximum(w_prev[under_low], low_trade[under_low]))
            high[under_low] = np.maximum(high[under_low], low[under_low])

    if np.any(low > high):
        bad = np.flatnonzero(low > high)[:10]
        raise RuntimeError(
            "Cost-aware optimizer produced infeasible per-asset bounds (low > high). "
            f"Sample bad indices={bad.tolist()}."
        )

    min_sum = float(low.sum())
    max_sum = float(high.sum())
    return low, high, float(requested_target_sum), float(min_sum), float(max_sum)


# Return the effective target sum after applying partial-fill rules when allowed.
def _resolve_effective_target_sum(
    *,
    params: CostAwareParams,
    requested_target_sum: float,
    min_sum: float,
    max_sum: float,
    desired_target_sum: Optional[float],
) -> float:
    target = float(requested_target_sum if desired_target_sum is None else desired_target_sum)

    if not np.isfinite(target):
        raise RuntimeError("Cost-aware optimizer received a non-finite desired_target_sum.")

    if params.long_only and not params.dollar_neutral and params.allow_partial_long_only:
        target = min(target, max_sum)
        target = max(target, min_sum)
        return float(target)

    if (target < min_sum - 1e-10) or (target > max_sum + 1e-10):
        raise RuntimeError(
            f"Cost-aware optimizer constraints are infeasible for target sum {target:.6f}; "
            f"feasible range is [{min_sum:.6f}, {max_sum:.6f}]."
        )
    return float(target)


# Return the feasible long-only target-sum interval implied by ADV caps and previous weights.
def compute_long_only_feasible_interval(
    *,
    w_prev: Union[pd.Series, Sequence[float], np.ndarray],
    adv: Union[pd.Series, Sequence[float], np.ndarray],
    aum: float,
    params: CostAwareParams,
) -> Tuple[float, float]:
    idx = pd.Index(pd.Series(w_prev).index.astype(str)) if isinstance(w_prev, pd.Series) else pd.Index(range(len(w_prev)))
    w_prev_vec = _coerce_vector(w_prev, idx, fill_value=np.nan)
    if not np.isfinite(w_prev_vec).all():
        raise RuntimeError("Feasible-interval helper received missing or non-finite previous weights.")
    adv_vec = _resolve_adv_vector(idx, adv)
    _, _, _, min_sum, max_sum = _compute_bounds_stats(
        n=len(idx),
        w_prev=w_prev_vec,
        adv_vec=adv_vec,
        aum=float(aum),
        params=params,
    )
    return float(min_sum), float(max_sum)


# Project weights onto the intersection of a box and a linear sum constraint.
# Project weights onto the intersection of box constraints and a linear sum constraint.
def _project_sum_and_box(
    w: np.ndarray,
    target_sum: float,
    low: np.ndarray,
    high: np.ndarray,
    max_iter: int = 200,
    tol: float = 1e-10,
) -> np.ndarray:
    z0 = np.asarray(w, dtype=float).copy()
    low = np.asarray(low, dtype=float)
    high = np.asarray(high, dtype=float)

    if z0.ndim != 1 or low.ndim != 1 or high.ndim != 1:
        raise RuntimeError("Projection expects 1D arrays.")
    if not (len(z0) == len(low) == len(high)):
        raise RuntimeError("Projection received mismatched vector lengths.")
    if np.any(low > high):
        raise RuntimeError("Projection received infeasible box bounds (low > high).")

    min_sum = float(low.sum())
    max_sum = float(high.sum())
    if target_sum < min_sum - 1e-10 or target_sum > max_sum + 1e-10:
        raise RuntimeError(
            f"Projection target_sum={target_sum:.6f} is outside feasible range "
            f"[{min_sum:.6f}, {max_sum:.6f}]."
        )

    # Handle edge cases exactly.
    if abs(target_sum - min_sum) <= tol:
        return low.copy()
    if abs(target_sum - max_sum) <= tol:
        return high.copy()

    # We want z = clip(w - lam, low, high) such that sum(z) = target_sum.
    def summed(lam: float) -> float:
        return float(np.clip(z0 - lam, low, high).sum())

    lo_lam = float(np.min(z0 - high))
    hi_lam = float(np.max(z0 - low))

    s_lo = summed(lo_lam)
    s_hi = summed(hi_lam)

    if s_lo < target_sum - 1e-10 or s_hi > target_sum + 1e-10:
        raise RuntimeError(
            "Projection bracketing failed; the target sum was not bracketed correctly."
        )

    for _ in range(max_iter):
        mid = 0.5 * (lo_lam + hi_lam)
        s_mid = summed(mid)

        if abs(s_mid - target_sum) <= tol:
            return np.clip(z0 - mid, low, high)

        if s_mid > target_sum:
            lo_lam = mid
        else:
            hi_lam = mid

    z = np.clip(z0 - 0.5 * (lo_lam + hi_lam), low, high)
    residual = float(target_sum - z.sum())
    if abs(residual) > 1e-8:
        raise RuntimeError(
            f"Projection could not satisfy the target sum constraint; residual={residual:.6e}."
        )
    return z


# Optionally rescale a long-short solution to a target gross exposure and re-project it.
def _apply_gross_target(
    w: np.ndarray,
    *,
    target_sum: float,
    low: np.ndarray,
    high: np.ndarray,
    params: CostAwareParams,
) -> np.ndarray:
    if params.long_only or params.gross_target is None or params.gross_target <= 0:
        return w
    gross = float(np.sum(np.abs(w)))
    if gross <= 1e-12 or not np.isfinite(gross):
        return w
    z = (float(params.gross_target) / gross) * w
    return _project_sum_and_box(z, target_sum, low, high)


# Smooth the absolute-value function for stable nonlinear optimization.
def _smoothed_abs(x: np.ndarray, eps: float) -> np.ndarray:
    return np.sqrt(np.square(x) + float(eps) ** 2)


# Build stock-specific nonlinear impact coefficients from volatility and liquidity.
def _impact_coeff_vector(
    *,
    sigma_vec: np.ndarray,
    adv_vec: np.ndarray,
    aum: float,
    impact_kappa: float,
    execution_days: float = 1.0,
) -> np.ndarray:
    days = float(execution_days)
    if (not np.isfinite(days)) or days <= 0.0:
        raise ValueError("execution_days must be a finite positive number of trading days.")
    execution_volume = np.clip(adv_vec * days, 1.0, None)
    with np.errstate(divide="ignore", invalid="ignore"):
        coeff = float(impact_kappa) * sigma_vec * np.sqrt(float(aum) / execution_volume)
    coeff = np.asarray(coeff, dtype=float)
    coeff[~np.isfinite(coeff)] = 0.0
    return np.clip(coeff, 0.0, None)


# Evaluate the smooth nonlinear objective in minimization form for backtracking.
def _smooth_objective(
    *,
    w: np.ndarray,
    w_prev: np.ndarray,
    alpha_vec: np.ndarray,
    G: np.ndarray,
    spreads_vec: np.ndarray,
    impact_coeff_vec: np.ndarray,
    params: CostAwareParams,
) -> float:
    delta = w - w_prev
    eps = float(params.impact_smooth_eps)
    eta_linear = float(params.resolved_eta_linear())
    eta_impact = float(params.eta_impact)
    p = float(params.impact_exponent)
    risk_and_alpha = 0.5 * float(w @ (G @ w)) - float(alpha_vec @ w)
    linear_cost = eta_linear * float(np.sum(spreads_vec * _smoothed_abs(delta, eps)))
    impact_cost = eta_impact * float(np.sum(impact_coeff_vec * np.power(np.square(delta) + eps**2, 0.5 * p)))
    return risk_and_alpha + linear_cost + impact_cost


# Evaluate the gradient of the smooth nonlinear objective.
def _smooth_gradient(
    *,
    w: np.ndarray,
    w_prev: np.ndarray,
    alpha_vec: np.ndarray,
    G: np.ndarray,
    spreads_vec: np.ndarray,
    impact_coeff_vec: np.ndarray,
    params: CostAwareParams,
) -> np.ndarray:
    delta = w - w_prev
    eps = float(params.impact_smooth_eps)
    eta_linear = float(params.resolved_eta_linear())
    eta_impact = float(params.eta_impact)
    p = float(params.impact_exponent)
    base_grad = G.dot(w) - alpha_vec
    linear_grad = eta_linear * spreads_vec * (delta / _smoothed_abs(delta, eps))
    impact_power = np.power(np.square(delta) + eps**2, 0.5 * p - 1.0)
    impact_grad = eta_impact * impact_coeff_vec * p * delta * impact_power
    return base_grad + linear_grad + impact_grad






# Evaluate the diagonal of the smooth objective Hessian for scaling and preconditioning.
def _smooth_hessian_diag(
    *,
    w: np.ndarray,
    w_prev: np.ndarray,
    G: np.ndarray,
    spreads_vec: np.ndarray,
    impact_coeff_vec: np.ndarray,
    params: CostAwareParams,
    floor: float = 1e-10,
) -> np.ndarray:
    delta = w - w_prev
    eps = float(params.impact_smooth_eps)
    eta_linear = float(params.resolved_eta_linear())
    eta_impact = float(params.eta_impact)
    p = float(params.impact_exponent)

    base = np.square(delta) + eps**2
    hdiag = np.diag(G).astype(float, copy=True)

    linear_hdiag = eta_linear * spreads_vec * (eps**2) / np.power(base, 1.5)
    impact_hdiag = eta_impact * impact_coeff_vec * p * (eps**2 + (p - 1.0) * np.square(delta)) * np.power(base, 0.5 * p - 2.0)

    hdiag = hdiag + linear_hdiag + impact_hdiag
    hdiag[~np.isfinite(hdiag)] = float(floor)
    return np.clip(hdiag, float(floor), None)


# Build a diagonal inverse-Hessian approximation used as the initial L-BFGS scaling.
def _diag_inverse_hessian0(
    *,
    w: np.ndarray,
    w_prev: np.ndarray,
    G: np.ndarray,
    spreads_vec: np.ndarray,
    impact_coeff_vec: np.ndarray,
    params: CostAwareParams,
    floor: float = 1e-10,
) -> np.ndarray:
    hdiag = _smooth_hessian_diag(
        w=w,
        w_prev=w_prev,
        G=G,
        spreads_vec=spreads_vec,
        impact_coeff_vec=impact_coeff_vec,
        params=params,
        floor=floor,
    )
    inv_hdiag = 1.0 / np.clip(hdiag, float(floor), None)
    inv_hdiag[~np.isfinite(inv_hdiag)] = 1.0 / float(floor)
    return inv_hdiag


# Check whether the configured smooth objective is in the intended strongly-convex regime.
def _is_strongly_convex_configuration(
    *,
    G: np.ndarray,
    spreads_vec: np.ndarray,
    impact_coeff_vec: np.ndarray,
    params: CostAwareParams,
) -> bool:
    if float(params.lambda_risk) <= 0.0:
        return False
    if float(params.resolved_eta_linear()) < 0.0:
        return False
    if float(params.eta_impact) < 0.0:
        return False
    if float(params.impact_exponent) < 1.0:
        return False
    if np.any(spreads_vec < 0.0):
        return False
    if np.any(impact_coeff_vec < 0.0):
        return False

    Gsym = 0.5 * (np.asarray(G, dtype=float) + np.asarray(G, dtype=float).T)
    if not np.isfinite(Gsym).all():
        return False
    try:
        np.linalg.cholesky(Gsym)
        return True
    except np.linalg.LinAlgError:
        return False


# Apply a projected Armijo line search along a proposed direction.
def _projected_armijo_line_search(
    *,
    w: np.ndarray,
    direction: np.ndarray,
    grad: np.ndarray,
    obj: float,
    w_prev: np.ndarray,
    alpha_vec: np.ndarray,
    G: np.ndarray,
    spreads_vec: np.ndarray,
    impact_coeff_vec: np.ndarray,
    params: CostAwareParams,
    target_sum: float,
    low: np.ndarray,
    high: np.ndarray,
    initial_step: float,
    c1: float = 1e-4,
) -> Tuple[np.ndarray, float, float, bool]:
    step_eff = max(float(initial_step), 1e-12)
    candidate = w.copy()
    cand_obj = float("inf")

    for _bt in range(int(params.max_backtracks)):
        candidate = w + step_eff * direction
        candidate = _project_sum_and_box(candidate, target_sum, low, high)
        candidate = _apply_gross_target(candidate, target_sum=target_sum, low=low, high=high, params=params)
        d = candidate - w
        cand_obj = _smooth_objective(
            w=candidate,
            w_prev=w_prev,
            alpha_vec=alpha_vec,
            G=G,
            spreads_vec=spreads_vec,
            impact_coeff_vec=impact_coeff_vec,
            params=params,
        )
        if np.isfinite(cand_obj) and cand_obj <= float(obj + c1 * np.dot(grad, d)):
            return candidate, float(cand_obj), float(step_eff), True
        step_eff *= 0.5

    return candidate, float(cand_obj), float(step_eff), False


# Run the L-BFGS two-loop recursion using the stored curvature pairs.
def _lbfgs_two_loop(
    *,
    grad: np.ndarray,
    s_hist: Sequence[np.ndarray],
    y_hist: Sequence[np.ndarray],
    h0_diag: np.ndarray,
) -> np.ndarray:
    if len(s_hist) != len(y_hist):
        raise RuntimeError("L-BFGS history received mismatched s/y lengths.")

    q = grad.astype(float, copy=True)
    alpha_vals: List[float] = []
    rho_vals: List[float] = []

    valid_pairs: List[Tuple[np.ndarray, np.ndarray]] = []
    for s, y in zip(s_hist, y_hist):
        sty = float(np.dot(s, y))
        if np.isfinite(sty) and sty > 1e-14:
            valid_pairs.append((s, y))

    for s, y in reversed(valid_pairs):
        rho = 1.0 / float(np.dot(s, y))
        alpha = rho * float(np.dot(s, q))
        q = q - alpha * y
        alpha_vals.append(alpha)
        rho_vals.append(rho)

    r = h0_diag * q

    for (s, y), alpha, rho in zip(valid_pairs, reversed(alpha_vals), reversed(rho_vals)):
        beta = rho * float(np.dot(y, r))
        r = r + s * (alpha - beta)

    return -r


# Solve the smooth projected problem with projected gradient, BB step guesses, and Armijo fallback.

# Choose the best projected initial point among several candidates.
def _select_initial_point(
    *,
    candidates: Sequence[np.ndarray],
    w_prev: np.ndarray,
    alpha_vec: np.ndarray,
    G: np.ndarray,
    spreads_vec: np.ndarray,
    impact_coeff_vec: np.ndarray,
    params: CostAwareParams,
    target_sum: float,
    low: np.ndarray,
    high: np.ndarray,
) -> Tuple[np.ndarray, float]:
    best_w: Optional[np.ndarray] = None
    best_obj = float("inf")
    for cand in candidates:
        z = _project_sum_and_box(np.asarray(cand, dtype=float), target_sum, low, high)
        z = _apply_gross_target(z, target_sum=target_sum, low=low, high=high, params=params)
        obj = _smooth_objective(
            w=z,
            w_prev=w_prev,
            alpha_vec=alpha_vec,
            G=G,
            spreads_vec=spreads_vec,
            impact_coeff_vec=impact_coeff_vec,
            params=params,
        )
        if np.isfinite(obj) and obj < best_obj:
            best_w = z.copy()
            best_obj = float(obj)

    if best_w is None:
        z = _project_sum_and_box(np.asarray(candidates[0], dtype=float), target_sum, low, high)
        z = _apply_gross_target(z, target_sum=target_sum, low=low, high=high, params=params)
        best_w = z
        best_obj = float(_smooth_objective(
            w=z,
            w_prev=w_prev,
            alpha_vec=alpha_vec,
            G=G,
            spreads_vec=spreads_vec,
            impact_coeff_vec=impact_coeff_vec,
            params=params,
        ))
    return best_w, best_obj


# Solve the smooth projected problem with projected gradient, BB step guesses, and Armijo fallback.
def _projected_armijo_solve(
    *,
    w_init: np.ndarray,
    w_prev: np.ndarray,
    alpha_vec: np.ndarray,
    G: np.ndarray,
    spreads_vec: np.ndarray,
    impact_coeff_vec: np.ndarray,
    params: CostAwareParams,
    target_sum: float,
    low: np.ndarray,
    high: np.ndarray,
    warn_label: str,
) -> Tuple[np.ndarray, bool]:
    w = _project_sum_and_box(np.asarray(w_init, dtype=float), target_sum, low, high)
    w = _apply_gross_target(w, target_sum=target_sum, low=low, high=high, params=params)

    obj = _smooth_objective(
        w=w,
        w_prev=w_prev,
        alpha_vec=alpha_vec,
        G=G,
        spreads_vec=spreads_vec,
        impact_coeff_vec=impact_coeff_vec,
        params=params,
    )
    best_w = w.copy()
    best_obj = float(obj)

    grad_prev: Optional[np.ndarray] = None
    w_prev_iter: Optional[np.ndarray] = None
    step_guess = max(float(params.step), 1e-8)
    converged = False

    for _ in range(int(params.max_iters)):
        grad = _smooth_gradient(
            w=w,
            w_prev=w_prev,
            alpha_vec=alpha_vec,
            G=G,
            spreads_vec=spreads_vec,
            impact_coeff_vec=impact_coeff_vec,
            params=params,
        )
        if not np.isfinite(grad).all():
            break

        inv_h0_diag = _diag_inverse_hessian0(
            w=w,
            w_prev=w_prev,
            G=G,
            spreads_vec=spreads_vec,
            impact_coeff_vec=impact_coeff_vec,
            params=params,
        )
        direction = -(inv_h0_diag * grad)
        if float(np.dot(grad, direction)) >= 0.0:
            direction = -grad

        if grad_prev is not None and w_prev_iter is not None:
            s = w - w_prev_iter
            y = grad - grad_prev
            sty = float(np.dot(s, y))
            sts = float(np.dot(s, s))
            if np.isfinite(sty) and np.isfinite(sts) and sty > 1e-14 and sts > 0.0:
                bb_step = sts / sty
                if np.isfinite(bb_step):
                    step_guess = float(np.clip(bb_step, 1e-8, 1e8))

        candidate, cand_obj, step_used, accepted = _projected_armijo_line_search(
            w=w,
            direction=direction,
            grad=grad,
            obj=float(obj),
            w_prev=w_prev,
            alpha_vec=alpha_vec,
            G=G,
            spreads_vec=spreads_vec,
            impact_coeff_vec=impact_coeff_vec,
            params=params,
            target_sum=target_sum,
            low=low,
            high=high,
            initial_step=step_guess,
        )
        if not accepted:
            break

        max_change = float(np.max(np.abs(candidate - w)))
        w_prev_iter = w.copy()
        grad_prev = grad.copy()
        w = candidate
        obj = float(cand_obj)
        step_guess = max(float(step_used), 1e-8)

        if np.isfinite(obj) and obj < best_obj:
            best_w = w.copy()
            best_obj = float(obj)

        if max_change < float(params.tol):
            converged = True
            break

    if not converged:
        warnings.warn(
            f"{warn_label} reached max_iters; returning best feasible iterate found.",
            RuntimeWarning,
            stacklevel=2,
        )
    return best_w, converged


# Solve the smooth projected problem with projected L-BFGS and safeguarded Armijo backtracking.
def _projected_lbfgs_solve(
    *,
    w_init: np.ndarray,
    w_prev: np.ndarray,
    alpha_vec: np.ndarray,
    G: np.ndarray,
    spreads_vec: np.ndarray,
    impact_coeff_vec: np.ndarray,
    params: CostAwareParams,
    target_sum: float,
    low: np.ndarray,
    high: np.ndarray,
    warn_label: str,
    memory: int = 10,
) -> Tuple[np.ndarray, bool, bool]:
    w = _project_sum_and_box(np.asarray(w_init, dtype=float), target_sum, low, high)
    w = _apply_gross_target(w, target_sum=target_sum, low=low, high=high, params=params)

    obj = _smooth_objective(
        w=w,
        w_prev=w_prev,
        alpha_vec=alpha_vec,
        G=G,
        spreads_vec=spreads_vec,
        impact_coeff_vec=impact_coeff_vec,
        params=params,
    )
    best_w = w.copy()
    best_obj = float(obj)

    grad = _smooth_gradient(
        w=w,
        w_prev=w_prev,
        alpha_vec=alpha_vec,
        G=G,
        spreads_vec=spreads_vec,
        impact_coeff_vec=impact_coeff_vec,
        params=params,
    )
    if not np.isfinite(grad).all():
        return best_w, False, False

    s_hist: List[np.ndarray] = []
    y_hist: List[np.ndarray] = []
    step_guess = max(float(params.step), 1e-8)
    converged = False

    for _ in range(int(params.max_iters)):
        h0_diag = _diag_inverse_hessian0(
            w=w,
            w_prev=w_prev,
            G=G,
            spreads_vec=spreads_vec,
            impact_coeff_vec=impact_coeff_vec,
            params=params,
        )
        if s_hist:
            direction = _lbfgs_two_loop(
                grad=grad,
                s_hist=s_hist,
                y_hist=y_hist,
                h0_diag=h0_diag,
            )
        else:
            direction = -(h0_diag * grad)

        if (not np.isfinite(direction).all()) or float(np.dot(grad, direction)) >= 0.0:
            direction = -(h0_diag * grad)
            if float(np.dot(grad, direction)) >= 0.0:
                direction = -grad

        candidate, cand_obj, step_used, accepted = _projected_armijo_line_search(
            w=w,
            direction=direction,
            grad=grad,
            obj=float(obj),
            w_prev=w_prev,
            alpha_vec=alpha_vec,
            G=G,
            spreads_vec=spreads_vec,
            impact_coeff_vec=impact_coeff_vec,
            params=params,
            target_sum=target_sum,
            low=low,
            high=high,
            initial_step=step_guess,
        )

        if not accepted:
            fallback_w, fallback_conv = _projected_armijo_solve(
                w_init=w,
                w_prev=w_prev,
                alpha_vec=alpha_vec,
                G=G,
                spreads_vec=spreads_vec,
                impact_coeff_vec=impact_coeff_vec,
                params=params,
                target_sum=target_sum,
                low=low,
                high=high,
                warn_label=f"{warn_label} fallback projected-gradient solver",
            )
            fallback_obj = _smooth_objective(
                w=fallback_w,
                w_prev=w_prev,
                alpha_vec=alpha_vec,
                G=G,
                spreads_vec=spreads_vec,
                impact_coeff_vec=impact_coeff_vec,
                params=params,
            )
            if np.isfinite(fallback_obj) and fallback_obj <= best_obj:
                return fallback_w, bool(fallback_conv), True
            break

        new_grad = _smooth_gradient(
            w=candidate,
            w_prev=w_prev,
            alpha_vec=alpha_vec,
            G=G,
            spreads_vec=spreads_vec,
            impact_coeff_vec=impact_coeff_vec,
            params=params,
        )
        if not np.isfinite(new_grad).all():
            break

        s = candidate - w
        y = new_grad - grad
        sty = float(np.dot(s, y))
        if np.isfinite(sty) and sty > 1e-14:
            if len(s_hist) >= int(memory):
                s_hist.pop(0)
                y_hist.pop(0)
            s_hist.append(s.copy())
            y_hist.append(y.copy())

        max_change = float(np.max(np.abs(candidate - w)))
        w = candidate
        grad = new_grad
        obj = float(cand_obj)
        step_guess = max(float(step_used), 1e-8)

        if np.isfinite(obj) and obj < best_obj:
            best_w = w.copy()
            best_obj = float(obj)

        if max_change < float(params.tol):
            converged = True
            break

    if not converged:
        warnings.warn(
            f"{warn_label} reached max_iters; returning best feasible iterate found.",
            RuntimeWarning,
            stacklevel=2,
        )
    return best_w, converged, False


# Compute realized linear and nonlinear trading costs from a trade vector.
def compute_trade_cost_breakdown(
    *,
    w: pd.Series,
    w_prev: pd.Series,
    spreads_oneway: pd.Series,
    sigma: Optional[pd.Series] = None,
    adv: Optional[pd.Series] = None,
    aum: float = 1.0,
    impact_kappa: float = 1.0,
    impact_exponent: float = 1.5,
    execution_days: float = 1.0,
) -> TradeCostBreakdown:
    w_use = _canonical_series(w, name="w")
    w_prev_use = _canonical_series(w_prev, name="w_prev")
    spreads_use = _canonical_series(spreads_oneway, name="spreads_oneway")
    idx = pd.Index(w_use.index)
    w_cur = pd.to_numeric(w_use.reindex(idx), errors="coerce")
    w_old = pd.to_numeric(w_prev_use.reindex(idx), errors="coerce")
    spreads = pd.to_numeric(spreads_use.reindex(idx), errors="coerce")
    if w_cur.isna().any() or w_old.isna().any() or spreads.isna().any():
        raise RuntimeError("Trade cost breakdown received missing aligned inputs.")
    spreads = spreads.abs()
    delta = (w_cur - w_old).abs()
    linear_cost = float((spreads * delta).sum())

    impact_cost = 0.0
    if sigma is not None and adv is not None:
        sigma_use = _canonical_series(sigma, name="sigma")
        adv_use = _canonical_series(adv, name="adv")
        sigma_vec = pd.to_numeric(sigma_use.reindex(idx), errors="coerce")
        adv_vec = pd.to_numeric(adv_use.reindex(idx), errors="coerce")
        if sigma_vec.isna().any() or adv_vec.isna().any():
            raise RuntimeError("Trade cost breakdown received missing sigma/adv inputs.")
        sigma_vec = sigma_vec.abs()
        adv_vec = adv_vec.clip(lower=1.0)
        coeff = pd.Series(
            _impact_coeff_vector(
                sigma_vec=sigma_vec.to_numpy(dtype=float),
                adv_vec=adv_vec.to_numpy(dtype=float),
                aum=float(aum),
                impact_kappa=float(impact_kappa),
                execution_days=float(execution_days),
            ),
            index=idx,
        )
        impact_cost = float((coeff * np.power(delta.to_numpy(dtype=float), float(impact_exponent))).sum())

    return TradeCostBreakdown(
        linear_cost=float(linear_cost),
        impact_cost=float(impact_cost),
        total_cost=float(linear_cost + impact_cost),
    )


# Solve the alpha-driven nonlinear-cost objective with smooth projected gradient and backtracking.
def solve_cost_aware_nonlinear_pg(
    *,
    alpha: pd.Series,
    Sigma: np.ndarray,
    w_prev: pd.Series,
    adv: pd.Series,
    sigma: pd.Series,
    aum: float,
    spreads_oneway: Optional[pd.Series] = None,
    spreads_bps: Optional[pd.Series] = None,
    params: Optional[CostAwareParams] = None,
    desired_target_sum: Optional[float] = None,
) -> pd.Series:
    alpha_use = _canonical_series(alpha, name="alpha")
    w_prev_use = _canonical_series(w_prev, name="w_prev")
    idx = pd.Index(alpha_use.index)
    if params is None:
        params = CostAwareParams()

    alpha_aligned = pd.to_numeric(alpha_use.reindex(idx), errors="coerce")
    w_prev_aligned = pd.to_numeric(w_prev_use.reindex(idx), errors="coerce")
    if alpha_aligned.isna().any():
        raise RuntimeError("Cost-aware optimizer received missing alpha inputs after alignment.")
    if w_prev_aligned.isna().any():
        raise RuntimeError("Cost-aware optimizer received missing previous weights after alignment.")
    alpha_vec = alpha_aligned.to_numpy(dtype=float)
    w0 = w_prev_aligned.to_numpy(dtype=float)
    adv_vec = _resolve_adv_vector(idx, adv)
    sigma_vec = _resolve_sigma_vector(idx, sigma)
    spreads_vec = _resolve_spreads_fraction(
        idx,
        spreads_oneway=spreads_oneway,
        spreads_bps=spreads_bps,
        default_bps=params.spread_bps_default,
    )
    impact_coeff_vec = _impact_coeff_vector(
        sigma_vec=sigma_vec,
        adv_vec=adv_vec,
        aum=float(aum),
        impact_kappa=float(params.impact_kappa),
        execution_days=params.resolved_execution_days(),
    )

    low, high, requested_target_sum, min_sum, max_sum = _compute_bounds_stats(
        n=len(idx),
        w_prev=w0,
        adv_vec=adv_vec,
        aum=float(aum),
        params=params,
    )
    target_sum = _resolve_effective_target_sum(
        params=params,
        requested_target_sum=requested_target_sum,
        min_sum=min_sum,
        max_sum=max_sum,
        desired_target_sum=desired_target_sum,
    )

    Sigma_arr = np.asarray(Sigma, dtype=float)
    if Sigma_arr.ndim != 2 or Sigma_arr.shape[0] != Sigma_arr.shape[1]:
        raise RuntimeError(f"Cost-aware optimizer expected a square covariance matrix; got shape {Sigma_arr.shape}.")
    if Sigma_arr.shape[0] != len(idx):
        raise RuntimeError(
            f"Cost-aware optimizer received a covariance matrix of size {Sigma_arr.shape[0]} for {len(idx)} assets."
        )
    if not np.isfinite(Sigma_arr).all():
        raise RuntimeError("Cost-aware optimizer received a covariance matrix with non-finite entries.")
    Sigma_arr = 0.5 * (Sigma_arr + Sigma_arr.T)
    G = 2.0 * float(params.lambda_risk) * Sigma_arr

    if abs(target_sum) <= 1e-12 and params.long_only and not params.dollar_neutral:
        out = pd.Series(np.zeros(len(idx), dtype=float), index=idx, name="w_opt")
        out.attrs["effective_target_sum"] = float(target_sum)
        out.attrs["requested_target_sum"] = float(requested_target_sum if desired_target_sum is None else desired_target_sum)
        out.attrs["min_feasible_sum"] = float(min_sum)
        out.attrs["max_feasible_sum"] = float(max_sum)
        out.attrs["solver_method"] = "no_trade_zero_target"
        out.attrs["solver_converged"] = True
        out.attrs["solver_fallback_used"] = False
        return out

    w_init, _ = _select_initial_point(
        candidates=[w0],
        w_prev=w0,
        alpha_vec=alpha_vec,
        G=G,
        spreads_vec=spreads_vec,
        impact_coeff_vec=impact_coeff_vec,
        params=params,
        target_sum=target_sum,
        low=low,
        high=high,
    )
    solver_method = "projected_gradient"
    solver_fallback_used = False
    if _is_strongly_convex_configuration(
        G=G,
        spreads_vec=spreads_vec,
        impact_coeff_vec=impact_coeff_vec,
        params=params,
    ):
        w_best, solver_converged, solver_fallback_used = _projected_lbfgs_solve(
            w_init=w_init,
            w_prev=w0,
            alpha_vec=alpha_vec,
            G=G,
            spreads_vec=spreads_vec,
            impact_coeff_vec=impact_coeff_vec,
            params=params,
            target_sum=target_sum,
            low=low,
            high=high,
            warn_label="Alpha-driven cost-aware optimizer",
        )
        solver_method = "lbfgs_to_projected_gradient" if solver_fallback_used else "lbfgs"
    else:
        warnings.warn(
            "Alpha-driven cost-aware optimizer is outside the intended strongly-convex regime; "
            "falling back to safeguarded projected gradient.",
            RuntimeWarning,
            stacklevel=2,
        )
        w_best, solver_converged = _projected_armijo_solve(
            w_init=w_init,
            w_prev=w0,
            alpha_vec=alpha_vec,
            G=G,
            spreads_vec=spreads_vec,
            impact_coeff_vec=impact_coeff_vec,
            params=params,
            target_sum=target_sum,
            low=low,
            high=high,
            warn_label="Alpha-driven cost-aware optimizer",
        )

    out = pd.Series(w_best, index=idx, name="w_opt")
    out.attrs["effective_target_sum"] = float(target_sum)
    out.attrs["requested_target_sum"] = float(requested_target_sum if desired_target_sum is None else desired_target_sum)
    out.attrs["min_feasible_sum"] = float(min_sum)
    out.attrs["max_feasible_sum"] = float(max_sum)
    out.attrs["solver_method"] = str(solver_method)
    out.attrs["solver_converged"] = bool(solver_converged)
    out.attrs["solver_fallback_used"] = bool(solver_fallback_used)
    return out


# Solve a target-tracking nonlinear rebalance problem around a fixed weight target.
def solve_rebalance_to_target_nonlinear_pg(
    *,
    w_target: pd.Series,
    w_prev: pd.Series,
    adv: pd.Series,
    sigma: pd.Series,
    aum: float,
    spreads_oneway: Optional[pd.Series] = None,
    spreads_bps: Optional[pd.Series] = None,
    params: Optional[CostAwareParams] = None,
    desired_target_sum: Optional[float] = None,
) -> pd.Series:
    target_use = _canonical_series(w_target, name="w_target")
    w_prev_use = _canonical_series(w_prev, name="w_prev")
    idx = pd.Index(target_use.index)
    if params is None:
        params = CostAwareParams()

    w_target_aligned = pd.to_numeric(target_use.reindex(idx), errors="coerce")
    w_prev_aligned = pd.to_numeric(w_prev_use.reindex(idx), errors="coerce")
    if w_target_aligned.isna().any():
        raise RuntimeError("Target-tracking optimizer received missing target weights after alignment.")
    if w_prev_aligned.isna().any():
        raise RuntimeError("Target-tracking optimizer received missing previous weights after alignment.")
    w_target_vec = w_target_aligned.to_numpy(dtype=float)
    w0 = w_prev_aligned.to_numpy(dtype=float)
    adv_vec = _resolve_adv_vector(idx, adv)
    sigma_vec = _resolve_sigma_vector(idx, sigma)
    spreads_vec = _resolve_spreads_fraction(
        idx,
        spreads_oneway=spreads_oneway,
        spreads_bps=spreads_bps,
        default_bps=params.spread_bps_default,
    )
    impact_coeff_vec = _impact_coeff_vector(
        sigma_vec=sigma_vec,
        adv_vec=adv_vec,
        aum=float(aum),
        impact_kappa=float(params.impact_kappa),
        execution_days=params.resolved_execution_days(),
    )

    low, high, requested_target_sum, min_sum, max_sum = _compute_bounds_stats(
        n=len(idx),
        w_prev=w0,
        adv_vec=adv_vec,
        aum=float(aum),
        params=params,
    )
    target_sum = _resolve_effective_target_sum(
        params=params,
        requested_target_sum=requested_target_sum,
        min_sum=min_sum,
        max_sum=max_sum,
        desired_target_sum=desired_target_sum,
    )

    target_penalty = max(float(params.target_penalty), 1e-12)
    target_total = float(np.nansum(w_target_vec))
    if target_total < 0:
        raise RuntimeError("Target-tracking optimizer received a target portfolio with negative total weight.")

    if target_sum <= 1e-12:
        scaled_target = np.zeros(len(idx), dtype=float)
    elif target_total <= 0 or not np.isfinite(target_total):
        scaled_target = np.full(len(idx), target_sum / max(len(idx), 1), dtype=float)
    else:
        scaled_target = w_target_vec * (float(target_sum) / target_total)

    G = target_penalty * np.eye(len(idx), dtype=float)
    alpha_vec = target_penalty * scaled_target

    w_init, _ = _select_initial_point(
        candidates=[w0, scaled_target],
        w_prev=w0,
        alpha_vec=alpha_vec,
        G=G,
        spreads_vec=spreads_vec,
        impact_coeff_vec=impact_coeff_vec,
        params=params,
        target_sum=target_sum,
        low=low,
        high=high,
    )
    w_best, solver_converged = _projected_armijo_solve(
        w_init=w_init,
        w_prev=w0,
        alpha_vec=alpha_vec,
        G=G,
        spreads_vec=spreads_vec,
        impact_coeff_vec=impact_coeff_vec,
        params=params,
        target_sum=target_sum,
        low=low,
        high=high,
        warn_label="Target-tracking cost-aware optimizer",
    )

    out = pd.Series(w_best, index=idx, name="w_opt")
    out.attrs["effective_target_sum"] = float(target_sum)
    out.attrs["requested_target_sum"] = float(requested_target_sum if desired_target_sum is None else desired_target_sum)
    out.attrs["min_feasible_sum"] = float(min_sum)
    out.attrs["max_feasible_sum"] = float(max_sum)
    out.attrs["solver_method"] = "projected_gradient"
    out.attrs["solver_converged"] = bool(solver_converged)
    out.attrs["solver_fallback_used"] = False
    return out


__all__ = [
    "CostAwareParams",
    "TradeCostBreakdown",
    "compute_long_only_feasible_interval",
    "compute_trade_cost_breakdown",
    "solve_cost_aware_nonlinear_pg",
    "solve_rebalance_to_target_nonlinear_pg",
]
